[package]
name = "arceos-priority"
version = "0.1.0"
edition = "2021"
authors = ["Haoxing Ye <yehx20@mails.tsinghua.edu.cn>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
sched_rr = ["axfeat/sched_rr"]
sched_cfs = ["axfeat/sched_cfs"]

[dependencies]
axstd = { path = "../../../ulib/axstd", features = ["alloc", "multitask"], optional = true }
axfeat = { path = "../../../api/axfeat", optional = true }
